version: "3.7"

services:
  electron-backend:
    build: .
    container_name: electron-backend
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./data:/data:rw"
    networks:
      - electron-network
    env_file: .env

networks:
  electron-network:
    name: electron-network